name: Erlang CI

on:
  push:
    branches: [ "electus" ]
  pull_request:
    branches: [ "electus" ]

permissions:
  contents: read

jobs:

  build:

    runs-on: ubuntu-latest

    container:
      image: erlang:25

    steps:
    - uses: actions/checkout@v4
    - name: Test
      run: make test
    - name: Dialyze
      run: make dialyze
